### ISSUE TITLE
move under /datalad org and upload release on pypi please

### ISSUE THREAD

**Issue by yarikoptic** [datalad/metadata-model#9]
it seems to be the "core" part of datalad-metalad, so probably should reside under datalad organization.

ATM I had to RTFM to get devel environment setup since it is not present on pypi at all (thus `pip install -e .` doesn't provide working installation of datalad-metalad) and needs installation using custom `requirements-devel.txt`.

**Comment by christian-monch** [comment]
datalad-metadata-model is uploaded as pypi-package.

**Comment by christian-monch** [comment]
moved to datalad. 

Sorry for the delay, somehow lost track of this issue
